@startuml SequenceDiagram

actor User

participant "Website" as Website
participant "Piano" as Piano
participant "MIDIAccessManager" as MIDIManager
participant "ChordLibrary" as ChordLib
participant "DragAndDropList" as DragDrop
participant "ProgressionGenerator" as ProgGen
participant "ChordFactory" as ChordFact
participant "ChordVoicing" as ChordVoice
participant "TabGenerator" as TabGen
participant "Chord" as Chord
participant "Utils" as Utils
participant "Constants" as Constants


== Initialization ==
Website -> Piano: Initialize Piano
activate Piano
Piano -> Piano: createPiano()
Piano -> Piano: addKeyListeners()
deactivate Piano

Website -> MIDIManager: Initialize MIDIManager
activate MIDIManager
MIDIManager -> MIDIManager: attemptMIDIAccess()
alt MIDI Access Success
    MIDIManager -> MIDIManager: onMIDISuccess()
    MIDIManager -> MIDIManager: addMIDIInputs(inputs)
    MIDIManager -> Website: Dispatch statusUpdated
else MIDI Access Failure
    MIDIManager -> MIDIManager: onMIDIFailure()
    MIDIManager -> MIDIManager: handleRetry()
end
deactivate MIDIManager

Website -> ChordLib: Initialize ChordLibrary
activate ChordLib
ChordLib -> ChordLib: generateChords()
deactivate ChordLib

Website -> DragDrop: Initialize DragAndDropList
activate DragDrop
DragDrop -> ChordLib: getAllChords()
DragDrop -> DragDrop: populateItemsList()
deactivate DragDrop

Website -> ProgGen: Initialize ProgressionGenerator
activate ProgGen
ProgGen -> ProgGen: setProgression(initialProgression)
deactivate ProgGen

== MIDI Input and Piano Interaction ==
MIDIManager -> MIDIManager: handleNoteOn(note)
MIDIManager -> Piano: Dispatch noteOn
User -> Piano: Selects Notes
activate Piano
Piano -> Piano: activateKey(note)
Piano -> ChordLib: searchChords(notes, rootNote)
activate ChordLib
ChordLib -> DragDrop: updateItems(searchResults)
deactivate ChordLib
deactivate Piano

MIDIManager -> MIDIManager: handleNoteOff(note)
MIDIManager -> Piano: Dispatch noteOff
User -> Piano: Deselects Notes
activate Piano
Piano -> Piano: deactivateKey(note)
Piano -> ChordLib: searchChords(notes, rootNote)
activate ChordLib
ChordLib -> DragDrop: updateItems(searchResults)
deactivate ChordLib
deactivate Piano

== Chord Progression Generation ==
User -> DragDrop: Add Chord to Progression
activate DragDrop
DragDrop -> ProgGen: setProgression(selectedItems)
deactivate DragDrop

activate ProgGen
ProgGen -> ProgGen: Calculates Delta to old Progression
ProgGen -> ChordFact: new ChordFactory(chord, useRoot, tuning)
activate ChordFact
ChordFact -> Constants: Import constants
ChordFact -> Utils: parseNotes(notes)
activate ChordVoice
ChordFact -> ChordVoice: new ChordVoicing(voicing, barre, fingersUsed, ...)
deactivate ChordVoice
ChordFact -> ProgGen: return ChordFactory instance
deactivate ChordFact

ProgGen -> ProgGen: analyzeKey()
ProgGen -> Website: Dispatch scaleDetected event
deactivate ProgGen

== Displaying Chord Diagrams ==
User -> ProgGen: Get Dynamic Progression
activate ProgGen
ProgGen -> ChordFact: sortPlayableChordsByCombinedRating(soundQuality)
ProgGen -> TabGen: new TabGenerator(chordVoicing.voicing, chordVoicing.fingerPositions, ...)
activate TabGen
TabGen -> Website: Display Chord Diagram
deactivate TabGen
deactivate ProgGen

== Playing Chord Progression ==
User -> Piano: Play Chord Progression
activate Piano
Piano -> Piano: playChord()
deactivate Piano

@enduml
